// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>

namespace IsomanagerWeb.Pages.Procesos
{
    public partial class GestionProcesos
    {
        /// <summary>
        /// Control litTituloPagina.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTituloPagina;

        /// <summary>
        /// Control litEvaluaciones.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litEvaluaciones;

        /// <summary>
        /// Control btnIrEvaluaciones.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnIrEvaluaciones;

        /// <summary>
        /// Control litCambios.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litCambios;

        /// <summary>
        /// Control btnIrCambios.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnIrCambios;

        /// <summary>
        /// Control litMejoras.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litMejoras;

        /// <summary>
        /// Control btnIrMejoras.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnIrMejoras;

        /// <summary>
        /// Control litAuditorias.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litAuditorias;

        /// <summary>
        /// Control btnIrAuditorias.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnIrAuditorias;

        /// <summary>
        /// Control txtBuscar.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBuscar;

        /// <summary>
        /// Control btnNuevoProceso.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnNuevoProceso;

        /// <summary>
        /// Control upProcesos.
        /// </summary>
        protected global::System.Web.UI.UpdatePanel upProcesos;

        /// <summary>
        /// Control lblMensaje.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMensaje;

        /// <summary>
        /// Control gvProcesos.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvProcesos;

        /// <summary>
        /// Control litTituloModal.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litTituloModal;

        /// <summary>
        /// Control upModal.
        /// </summary>
        protected global::System.Web.UI.UpdatePanel upModal;

        /// <summary>
        /// Control hdnProcesoId.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnProcesoId;

        /// <summary>
        /// Control txtNombre.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtNombre;

        /// <summary>
        /// Control rfvNombre.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvNombre;

        /// <summary>
        /// Control txtPropietario.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPropietario;

        /// <summary>
        /// Control txtObjetivo.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtObjetivo;

        /// <summary>
        /// Control txtDescripcion.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDescripcion;

        /// <summary>
        /// Control ucArea.
        /// </summary>
        protected global::Isomanager.Controls.ucDepartamentoSelector ucArea;

        /// <summary>
        /// Control ucResponsable.
        /// </summary>
        protected global::IsomanagerWeb.Controls.ucUsuarioSelector ucResponsable;

        /// <summary>
        /// Control ucAdministrador.
        /// </summary>
        protected global::IsomanagerWeb.Controls.ucUsuarioSelector ucAdministrador;

        /// <summary>
        /// Control ddlEstado.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlEstado;

        /// <summary>
        /// Control txtFechaInicio.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFechaInicio;

        /// <summary>
        /// Control txtFechaFin.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFechaFin;

        /// <summary>
        /// Control txtProgreso.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtProgreso;

        /// <summary>
        /// Control lblErrorModal.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblErrorModal;

        /// <summary>
        /// Control btnGuardarProceso.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnGuardarProceso;
    }
}
